### ISSUE TITLE
Сommands do not work on the server UM.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/ServerUtilities#130]
Mod version ServerUtilities-2.0.84
In a single game, the command home/sethome works. If the server is ultramain, then in the log there is such an inscription when trying to execute the command /sethome home

[19:07:01] [ERRO] Couldn't process command
java.lang.NullPointerException
        at serverutils.ranks.Rank.getPermission(Rank.java:209)
        at serverutils.ranks.PlayerRank.getPermission(PlayerRank.java:112)
        at serverutils.ranks.Rank.getPermissionValue(Rank.java:226)
        at serverutils.ranks.PlayerRank.getPermissionValue(PlayerRank.java:122)
        at serverutils.ranks.Ranks.getPermission(Ranks.java:507)
        at serverutils.ranks.Ranks.getPermissionResult(Ranks.java:515)
        at serverutils.ranks.Ranks.getPermissionResult(Ranks.java:520)
        at net.minecraft.command.CommandHandler.modifyExpressionValue$zba000$serverutilities$checkPermission(CommandHandler.java:543)
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:45)
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:759)
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:738)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)

**Comment by Pilad** [comment]
ranks add Pilad admin
[19:12:10] [INFO] Added rank admin as parent for Pilad
Tried to use sethome again, error again
[19:12:20] [ERRO] Couldn't process command
java.lang.NullPointerException
        at serverutils.ranks.Rank.getPermission(Rank.java:209)
        at serverutils.ranks.PlayerRank.getPermission(PlayerRank.java:112)
        at serverutils.ranks.Rank.getPermissionValue(Rank.java:226)
        at serverutils.ranks.PlayerRank.getPermissionValue(PlayerRank.java:122)
        at serverutils.ranks.Ranks.getPermission(Ranks.java:507)
        at serverutils.ranks.Ranks.getPermissionResult(Ranks.java:515)
        at serverutils.ranks.Ranks.getPermissionResult(Ranks.java:520)
        at net.minecraft.command.CommandHandler.modifyExpressionValue$zba000$serverutilities$checkPermission(CommandHandler.java:543)
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:45)
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:759)
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:738)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:231)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:567)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:444)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:719)

**Comment by Pilad** [comment]
> Turn off command permissions for now, ultramine makes some pretty hefty changes to some minecraft classes so it's unlikely to be supported.
On the ServerUtilities-2.0.79 mod version, you don't need to disable anything, it still worked there.

**Comment by boubou19** [comment]
yes but that's because SU evolved. UM and other hybrid servers are unsupported. Your options are:
- disabling the problematic stuff
- don't update SU
- Patch UM so SU works out of the box again

We aim to slowly provide all the usual stuff required on hybrid servers as plain forge alternative. So it's more likely to encounter more incompatibilities in the future.

**Comment by Pilad** [comment]
I see. Thanks for the clarification.

**Comment by Pilad** [comment]
> yes but that's because SU evolved. UM and other hybrid servers are unsupported. Your options are:
> 
>     * disabling the problematic stuff
> 
>     * don't update SU
> 
>     * Patch UM so SU works out of the box again
> 
> 
> We aim to slowly provide all the usual stuff required on hybrid servers as plain forge alternative. So it's more likely to encounter more incompatibilities in the future.

And how to correctly register a line with rights, for example, to a point at home? I tried this line, it does not work
- serverutilities.commands.home

**Comment by Lyfts** [comment]
Use the rank edit gui in the admin panel

**Comment by Pilad** [comment]
> Use the rank edit gui in the admin panel

The problem is that there is no button. And I mean you need to register the permission in the plugin, for example the same PEX or rights in the Thermos server or in Ultramine.
![изображение](https://github.com/user-attachments/assets/55ff398e-2bac-45bb-b3a4-4672a070c982)
![изображение](https://github.com/user-attachments/assets/07b22635-918b-4437-8939-012245ae3e45)

**Comment by Pilad** [comment]
For example, for a quest mod, you need to enter these lines into the plugin. So that they work not for the server operator.- betterquesting.commands.BQ_CommandAdmin
- betterquesting.commands.BQ_CommandUser

**Comment by Lyfts** [comment]
Questions regarding bukkit based permission systems are not really relevant here.

**Comment by Pilad** [comment]
For original mod :

### How to allow player to use an OP command?
Set `command.name` permission to `true`. If command is from mod, then it will have modid in it. For example, `/tp` will be `command.tp` but `/spawn` will be `command.ftbutilities.spawn`.

**Comment by Lyfts** [comment]
You only have to look a few messages above for that same message

**Comment by Pilad** [comment]
> You only have to look a few messages above for that same message

Thank you for your time. The blocking of commands comes from server utilities. I set up ranks in a single game, added a folder from the client to the server. Now everything works on ultramine.
