### ISSUE TITLE
Some functions do not work when installing sampler

### ISSUE THREAD

**Issue by InoryS** [GTNewHorizons/ServerUtilities#53]
Java 21
GTNH 2.5.1 Dedicated server
ServerUtilities-2.0.28

If I install sampler-1.60.1.jar
https://www.curseforge.com/minecraft/mc-mods/sampler
Then I won't be able to open the team interface, and I won't be able to use /dump_permissions

```
[14:47:22] [Server thread/ERROR]: Couldn't process command: 'dump_permissions'
java.lang.ExceptionInInitializerError
        at sampler.bg.<init>(F:46) ~[sampler-1.60.1.jar:?]
        at sampler.bg.<clinit>(F:12) ~[sampler-1.60.1.jar:?]
        at sampler.R.func_71518_a(F:34) ~[sampler-1.60.1.jar:?]
        at serverutils.ranks.CommandOverride.func_71518_a(CommandOverride.java:60) ~[CommandOverride.class:?]
        at serverutils.command.CmdDumpPermissions.func_71515_b(CmdDumpPermissions.java:153) ~[CmdDumpPermissions.class:?]
        at serverutils.ranks.CommandOverride.func_71515_b(CommandOverride.java:70) ~[CommandOverride.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: classes
        at sampler.c.a(F:38) ~[sampler-1.60.1.jar:?]
        at sampler.ab.<clinit>(F:6021) ~[sampler-1.60.1.jar:?]
        ... 18 more
Caused by: java.lang.NoSuchFieldException: classes
        at java.base/java.lang.Class.getDeclaredField(Class.java:2782) ~[?:?]
        at sampler.c.a(F:33) ~[sampler-1.60.1.jar:?]
        at sampler.ab.<clinit>(F:6021) ~[sampler-1.60.1.jar:?]
        ... 18 more

```

Also, I can't open the My Team page in creative mode, clicking -> loading progress bar -> automatically returning to the backpack page. Maybe it will open once in 70 clicks.
And the Trash Can page can always be opened, but the Claimed Chunk page sometimes cannot be opened.

**Comment by Lyfts** [comment]
That mod is an obfuscated mess that I really wouldn't recommend using. Through a bit of testing I've found that it's not SU causing the problems but rather lwjgl3ify and it will run fine if you use Java 8. 
The reason it's failing during /dump_permissions is simply due to sampler's command usage being checked. Doing /sampler alone causes the same problem. 

I haven't been able to reproduce your problem with pages not opening but feel free to open a new ticket if that continues after removing sampler.
